version: '3'
services:

  webserver:
    image: 'nginx:latest'
    depends_on:
      - php
    user: ${CURRENT_UID}
    restart: always
    ports:
      - "80:8000"
    volumes:
      - '../src/:/code'
      - './config/nginx/nginx_default_site.conf:/etc/nginx/conf.d/default.conf'
      - './config/nginx/nginx.conf:/etc/nginx/nginx.conf'

  php:
    build:
      context: ./images
      dockerfile: php.docker
    user: ${CURRENT_UID}
    container_name: php
    restart: always
    volumes:
      - '../src:/code'

  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.2
    container_name: logstash
    expose:
      - 9001
    environment:
      LS_JAVA_OPTS: "-Xms500m -Xmx500m -XX:ParallelGCThreads=1"
    volumes:
      - './config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml'
      - './config/logstash/logstash.conf:/usr/share/logstash/config/logstash_simple.conf'
    entrypoint:
      - logstash
      - -f
      - /usr/share/logstash/config/logstash_simple.conf